# Spins up two mailservers that can talk to each other over port 25.

version: '2.1'
services:

  sender:
    build: .
    # container_name: sender
    hostname: sender
    networks:
      - priv-net
    ports:
      - "25"

  recipient:
    build: .
    # container_name: recipient
    hostname: recipient
    networks:
      - priv-net
    ports:
      - "25"

networks:
  priv-net:
    driver: bridge
